### ISSUE TITLE
Strange highlighting with inline code samples

### ISSUE THREAD

**Issue by DavidDaish** [siko1056/language-sphinx#4]
I have found a strange highlighting bug with [inline code samples](http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html?highlight=external%20link#inline-markup). When using the syntax for inline code samples:

```
 You should use the ``fun_times(arg)`` function.
```

The highlighting will highlight the entire page when there is no whitespace before the accents.

Example of correct highlighting:
![screenshot from 2018-06-29 10-07-02](https://user-images.githubusercontent.com/22674032/42063082-38dcb4c4-7b84-11e8-99d9-ec3a379ad38b.png)

Example of highlighting error:
![screenshot from 2018-06-29 10-07-51](https://user-images.githubusercontent.com/22674032/42063106-51dab7a0-7b84-11e8-906e-bfa540591e31.png)

Strangely enough, the highlighting will stop if it encounters an [external link](http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html?highlight=external%20link#hyperlinks):

![screenshot from 2018-06-29 10-09-31](https://user-images.githubusercontent.com/22674032/42063216-c3944d5c-7b84-11e8-8a45-2337ac1152e6.png)

I tried to fix this issue myself, but I am not familiar enough with Atom or regex.

Thank you for the fantastic package.

**Comment by siko1056** [comment]
This one should also be closed by 2a7c0980f17c54ce86a3668edba3ab99fa52519b, can you provide some feedback, after the v0.1.8 release is out soon?

Thank you for #5 , it is motivating to see interest in this package :wink:

**Comment by DavidDaish** [comment]
Hi @siko1056! I've given it a test, and everything seems to be working. It's great to see this bug fixed, it's a great improvement. Thanks for accepting my merge request.
